def start_screen():
	print("WELCOME TO ANDELA LEARNING MAP TRACKER")
	print("======================================")
	print("BELOW IS A LIST OF SKILLS TESTED")
	print("--------------------------------")
	print("1.Version Control")
	print("2.Agile Methodology")
	print("3.Programming Logic")
	print("4.Object Oriented Programming")
	print("5.Test-Driven Development")
	print("6.Databases")
	print("7.HTTP and Web Services")
	print("8.Growth Mindset")
	print("Relationship Building")
	print("Asks Questions")
	print("Motivation and Commitment")
	print("Adaptability")
	print("Seeks Feedback")
	print("Speaking to be Understood")
	print("Writing Professionally")
	print("Git \n")
	print("======================================")
	print("PRESS ENTER TO CONTINUE")

	print("	")

start_screen()